Fix bug: test_helper.rb:19: undefined method `fixture_path=' for Test::Unit::TestCase:Class (NoMethodError)
The fix is to require rails 2.2.3. This will have to change for Rails 2.3.x.